export const AUDIT_ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_DELETED: 'USER_DELETED',

  CLIENT_PROFILE_CREATED: 'CLIENT_PROFILE_CREATED',
  CLIENT_PROFILE_APPROVED: 'CLIENT_PROFILE_APPROVED',
  DRIVER_PROFILE_CREATED: 'DRIVER_PROFILE_CREATED',

  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_VALIDATED: 'ORDER_VALIDATED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_ASSIGNED: 'ORDER_ASSIGNED',
  ORDER_IN_TRANSIT: 'ORDER_IN_TRANSIT',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  TRUCK_CREATED: 'TRUCK_CREATED',
  TRUCK_UPDATED: 'TRUCK_UPDATED',
  TRUCK_DELETED: 'TRUCK_DELETED',
  TRUCK_ASSIGNED: 'TRUCK_ASSIGNED',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export const AUDIT_RESOURCES = {
  USER: 'USER',
  CLIENT_PROFILE: 'CLIENT_PROFILE',
  DRIVER_PROFILE: 'DRIVER_PROFILE',
  ORDER: 'ORDER',
  TRUCK: 'TRUCK',
} as const

export type AuditResource = (typeof AUDIT_RESOURCES)[keyof typeof AUDIT_RESOURCES]
